### ISSUE TITLE
Interactive starrating on mobile (Iphone, safari): text box below needs some space

### ISSUE THREAD

**Issue by jorivdbosch** [fireball-conversation-design/ikea-idea-evaluation-on-the-go-170701#39]
![image3](https://user-images.githubusercontent.com/21040185/28124066-eda1df28-6722-11e7-82f6-4045556f7a71.PNG)

**Comment by RachelRomee** [comment]
not only on mobile!
![image](https://user-images.githubusercontent.com/12393064/28124675-ac68ae68-6724-11e7-9b30-8ecd9b5ee4b3.png)
