### ISSUE TITLE
q11x# - total at the bottom should be removed: CN and DE

### ISSUE THREAD

**Issue by MichelleGem** [fireball-conversation-design/ikea-idea-evaluation-on-the-go-170701#43]
<img width="663" alt="schermafbeelding 2017-07-12 om 17 05 06" src="https://user-images.githubusercontent.com/23661812/28124576-58c7a3ae-6724-11e7-8f31-136e3a06b1f3.png">

**Comment by RachelRomee** [comment]
Find `total:`  in language manager!
