### ISSUE TITLE
Chat tool: Jess is a block in Explorer - and not responsive everywhere!

### ISSUE THREAD

**Issue by jorivdbosch** [fireball-conversation-design/ikea-idea-evaluation-on-the-go-170701#48]
![image](https://user-images.githubusercontent.com/21040185/28124917-505c40b6-6725-11e7-86a5-43050a110561.png)

**Comment by RachelRomee** [comment]
![image](https://user-images.githubusercontent.com/12393064/28125176-204c4672-6726-11e7-9d80-1802409fd29c.png)
