### ISSUE TITLE
q6botg - an option is italic and shouldn't be

### ISSUE THREAD

**Issue by MichelleGem** [fireball-conversation-design/ikea-idea-evaluation-on-the-go-170701#50]
Why is 1 bis 2 Jahre italic?

<img width="621" alt="schermafbeelding 2017-07-12 om 17 16 50" src="https://user-images.githubusercontent.com/23661812/28125132-fcfbe52e-6725-11e7-9b0a-c46a67e3faae.png">

**Comment by vincentstoop** [comment]
Because in the translation there were i tags around it...
