### ISSUE TITLE
q16: Yes "active" should be green instead of orange

### ISSUE THREAD

**Issue by jorivdbosch** [fireball-conversation-design/ikea-idea-evaluation-on-the-go-170701#52]
![image](https://user-images.githubusercontent.com/21040185/28125308-85587c98-6726-11e7-958f-2380eda71fee.png)

**Comment by MichelleGem** [comment]
is this easy to over wright the orange color? 
Because then we can do:
not active = @green-3 & @red-3
active = @green-5& @red-5

Let me know if we want to try this out, would like to see the result

**Comment by vincentstoop** [comment]
Issue moved to [fireball-conversation-design/fireball-boilerplate-v2 #388](https://github.com/fireball-conversation-design/fireball-boilerplate-v2/issues/388) via [**ZenHub**](https://www.zenhub.com/)
